name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.0
  image_picker: ^0.8.5
  http: ^0.13.4
  http_auth: ^1.0.1
  intl: ^0.17.0
  # third parts
  flutter_colorpicker: ^1.0.3
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.1.1
  # storage auth
  googleapis_auth: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # third parts
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/launcher_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icons/
    - assets/carousel_images/

  fonts:
    - family: Ar
      fonts:
        - asset: assets/fonts/ar.ttf